name: Generate API Reference
on: 
  push:
    paths:
      - "docs/api-reference.json"
    branches: [main]
  workflow_dispatch:
jobs:
  generate-api-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate
        working-directory: scripts
        run: ./generate-api-reference.js

      - name: Commit
        run: |
          git config --global user.email "bot@raycast.com"
          git config --global user.name "raycastbot"

          if ! [[ -z $(git status -s) ]] ; then
            git add .
            git status .
            git commit --message "Docs: Generate API reference"
            git push -u origin $(git rev-parse --abbrev-ref HEAD)
          else
            echo "No changes, skipping sync."
          fi
      - name: Notify Failure to Slack
        if: failure()
        uses: edge/simple-slack-notify@master
        with:
          color: "danger"
          text: ":no_entry_sign: ${env.GITHUB_WORKFLOW} has failed"
          fields: |
            [
              { "title": "Action logs:", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
              { "title": "Commit:", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/commit/${ env.GITHUB_SHA }"}
            ]
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_STORE_REVIEW_CHANNEL_WEBHOOK_URL }}
